# Generated by Django 4.1.3 on 2023-04-07 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
