# Generated by Django 4.1.3 on 2022-12-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_generation_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
