# Generated by Django 4.1.3 on 2022-12-07 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_user_email_code_user_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_generation_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
