# Generated by Django 4.1.3 on 2022-12-06 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_user_email_code_user_is_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_code',
        ),
    ]
