# Generated by Django 4.1.3 on 2022-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_alter_user_code_generation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(null=True),
        ),
    ]
