# Generated by Django 4.1.3 on 2022-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_alter_user_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
