# Generated by Django 4.1.3 on 2022-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_remove_user_email_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
