# Generated by Django 4.1.3 on 2023-04-08 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_ticketsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsale',
            old_name='active_date',
            new_name='effective_date',
        ),
    ]
