# Generated by Django 4.1.3 on 2023-04-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_alter_event_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('career_prospects', 'Career Prospects'), ('social_connections', 'Social Connections'), ('personal_growth', 'Personal Growth'), ('partylike', 'Partylike')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
