# Generated by Django 4.1.3 on 2023-04-04 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invite.models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0006_alter_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=invite.models.Personalization.categories_dict)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_personalization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
