# Generated by Django 4.1.3 on 2023-04-08 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0006_alter_ticketsale_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
