# Generated by Django 4.1.3 on 2023-04-04 16:13

from django.db import migrations, models
import invite.models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0007_personalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalization',
            name='tags',
            field=models.JSONField(default=invite.models.Personalization.empty_dict),
        ),
    ]
