# Generated by Django 4.1.3 on 2023-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0007_event_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='identifier',
            field=models.CharField(default=123456, max_length=30),
            preserve_default=False,
        ),
    ]
