# Generated by Django 4.1.3 on 2023-01-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0008_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='/static/invite/images/profiles/default.png', upload_to='invite/static/invite/images/profiles'),
        ),
    ]
