# Generated by Django 4.1.3 on 2023-04-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0008_alter_personalization_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_keyword', to='invite.event')),
            ],
        ),
    ]
