# Generated by Django 4.1.3 on 2023-02-14 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0009_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_generation_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_code',
            field=models.IntegerField(default=0),
        ),
    ]
