# Generated by Django 4.1.3 on 2023-02-19 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0009_alter_profile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_recent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
