# Generated by Django 4.1.3 on 2023-02-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0010_alter_user_code_generation_date_and_more'),
        ('invite', '0010_recent'),
    ]

    operations = [
    ]
