# Generated by Django 4.1.3 on 2023-03-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0018_event_ticket_option_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket_option',
            new_name='ticket_access',
        ),
    ]
