# Generated by Django 4.1.3 on 2023-03-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0020_savedevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedEvents',
            new_name='SavedEvent',
        ),
    ]
