# Generated by Django 4.1.3 on 2023-03-11 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0021_rename_savedevents_savedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActionsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.ManyToManyField(related_name='event_attendees', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_actions', to='invite.event')),
                ('saves', models.ManyToManyField(related_name='event_saves', to='invite.savedevent')),
            ],
        ),
    ]
