### THE INFORMATION INSIDE THIS FILE IS PRIVATE AND TOP-SECRET

# NOTE: THESE CONFIGURATION SETTINGS ARE SUBJECT TO CHANGE AT ANY MOMENT
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'postmaster@livingdreams.rocks'
EMAIL_HOST_PASSWORD = '2872e013a779422c370c2e6160b08f04-d117dd33-e01092b8'

# API KEYS
MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoibnFhYmVuaGxlIiwiYSI6ImNsZXd6bjIwajBqdDUzb2tjY2lmamhqaWIifQ.3OexVyKsfjbGleSJhc3JxQ'
OPENAI_ACCESS_TOKEN = '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'

### COPY THIS TO RUN APPLICATION

# EMAIL_HOST = config.EMAIL_HOST
# EMAIL_PORT = config.EMAIL_PORT
# EMAIL_HOST_USER = config.EMAIL_HOST_USER
# EMAIL_HOST_PASSWORD = config.EMAIL_HOST_PASSWORD
# EMAIL_USE_TLS = True

# MAPBOX_ACCESS_TOKEN = config.MAPBOX_ACCESS_TOKEN
# OPENAI_ACCESS_TOKEN = config.OPENAI_ACCESS_TOKEN

### Import config: from . import config
### Remember to remove the import before committing your changes


### COPY THIS BEFORE PUSHING TO GITHUB:

# EMAIL_HOST = environ['HOST']
# EMAIL_PORT = environ['EMAIL_PORT']
# EMAIL_HOST_USER = environ['USER']
# EMAIL_HOST_PASSWORD = environ['PASSWORD']
# EMAIL_USE_TLS = True


### REMEMBER TO UNCOMMENT AFTER COPYING